services:
  supplier_creator:
    DATABASE_URL: mysql+pymysql://SVC_DS_HELPER:Abcd1234@rdb1.kaskade.local:3306/inventory
    WAIT_TIME: [3600, 7200]
    # WAIT_TIME: [1, 3]
    TYPE: ['music','vehicle']
    NUM_PROCESSES: 1
    RETENTION_HOUR: 2160

