services:
  invoices_creator:
    DATABASE_URL: mssql+pyodbc://SVC_DS_HELPER:Abcd1234@rdb1.kaskade.local:1433/inventory?driver=ODBC+Driver+17+for+SQL+Server
    NUM_PROCESSES: 2
    WAIT_TIME: [5,20]
    CLASS: ABCDEFG
    RETENTION_HOURS: 240
  invoices_modifier:
    DATABASE_URL: mssql+pyodbc://SVC_DS_HELPER:Abcd1234@rdb1.kaskade.local:1433/inventory?driver=ODBC+Driver+17+for+SQL+Server
    NUM_PROCESSES: 2
    WAIT_TIME: [5,20]
    CLASS: STUVWX

  orders_creator:
    DATABASE_URL: mssql+pyodbc://SVC_DS_HELPER:Abcd1234@rdb1.kaskade.local:1433/inventory?driver=ODBC+Driver+17+for+SQL+Server
    NUM_PROCESSES: 2
    WAIT_TIME: [5,20]
    STATUS:
      created: 50
      pending: 8
      shipped: 20
      delivered: 10
      others: 12
    RETENTION_HOURS: 240

  orders_demo00_creator:
    DATABASE_URL: mssql+pyodbc://SVC_DS_HELPER:Abcd1234@rdb1.kaskade.local:1433/inventory?driver=ODBC+Driver+17+for+SQL+Server
    NUM_PROCESSES: 2
    WAIT_TIME: [5,20]
    TYPE: [{"name":"vehicle", "provider":"VehicleProvider", "method":"fake.vehicle_object()"},{"name":"music","provider":"MusicProvider","method":"fake.music_genre_object()"}]
    STATUS:
      created: 50
      pending: 8
      shipped: 20
      delivered: 10
      others: 12
    RETENTION_HOURS: 240

  orders_demo00_modifier:
    DATABASE_URL: mssql+pyodbc://SVC_DS_HELPER:Abcd1234@rdb1.kaskade.local:1433/inventory?driver=ODBC+Driver+17+for+SQL+Server
    NUM_PROCESSES: 2
    WAIT_TIME: [5,20]
    STATUS:
      cancelled: 8
      shipped: 12
      delivered: 40
      completed: 40
    RAND_LAST_HOURS: 12

  orders_demo00_purger:
    DATABASE_URL: mssql+pyodbc://SVC_DS_HELPER:Abcd1234@rdb1.kaskade.local:1433/inventory?driver=ODBC+Driver+17+for+SQL+Server
    NUM_PROCESSES: 1
    WAIT_TIME: [6,12]
    RETENTION_HOURS: 48
    BATCH_SIZE: 500
