services:

  orders_creator:
    DATABASE_URL: mssql+pyodbc://sql_helper:Cc123456@db01.kaskade.local:1433/inventory?driver=ODBC+Driver+17+for+SQL+Server
    NUM_PROCESSES: 4
    WAIT_TIME: [5,10]
    STATUS:
      created: 50
      pending: 8
      shipped: 20
      delivered: 10
      others: 12
    RETENTION_HOURS: 240

  orders_demo00_creator:
    DATABASE_URL: mssql+pyodbc://sql_helper:Cc123456@db01.kaskade.local:1433/inventory?driver=ODBC+Driver+17+for+SQL+Server
    NUM_PROCESSES: 12
    WAIT_TIME: [1,7]
    TYPE: [{"name":"vehicle", "provider":"VehicleProvider", "method":"fake.vehicle_object()"},{"name":"music","provider":"MusicProvider","method":"fake.music_genre_object()"}]
    STATUS:
      created: 50
      pending: 8
      shipped: 20
      delivered: 10
      others: 12
    RETENTION_HOURS: 240

  orders_demo00_modifier:
    DATABASE_URL: mssql+pyodbc://sql_helper:Cc123456@db01.kaskade.local:1433/inventory?driver=ODBC+Driver+17+for+SQL+Server
    NUM_PROCESSES: 4
    WAIT_TIME: [5,15]
    STATUS:
      cancelled: 8
      shipped: 12
      delivered: 40
      completed: 40
    RAND_LAST_HOURS: 12

  orders_demo00_purger:
    DATABASE_URL: mssql+pyodbc://sql_helper:Cc123456@db01.kaskade.local:1433/inventory?driver=ODBC+Driver+17+for+SQL+Server
    NUM_PROCESSES: 1
    WAIT_TIME: [6,12]
    RETENTION_HOURS: 48
    BATCH_SIZE: 500
