services:
  invoices_creator:
    DATABASE_URL: mssql+pyodbc://SVC_DS_HELPER:Abcd1234@rdb1.kaskade.local:1433/inventory?driver=ODBC+Driver+17+for+SQL+Server
    WAIT_TIME: [30,60]
    CLASS: ABCDEFG
    NUM_PROCESSES: 4
    RETENTION_HOUR: 24
  invoices_modifier:
    DATABASE_URL: mssql+pyodbc://SVC_DS_HELPER:Abcd1234@rdb1.kaskade.local:1433/inventory?driver=ODBC+Driver+17+for+SQL+Server
    WAIT_TIME: [30, 60]
    CLASS: STUVWX
    NUM_PROCESSES: 8
  orders_creator:
    DATABASE_URL: mssql+pyodbc://SVC_DS_HELPER:Abcd1234@rdb1.kaskade.local:1433/inventory?driver=ODBC+Driver+17+for+SQL+Server
    WAIT_TIME: [30,60]
    STATUS:
      created: 50
      pending: 8
      shipped: 20
      delivered: 10
      others: 12
    NUM_PROCESSES: 4
    RETENTION_HOUR: 72
  orders_demo00_creator:
    DATABASE_URL: mssql+pyodbc://SVC_DS_HELPER:Abcd1234@rdb1.kaskade.local:1433/inventory?driver=ODBC+Driver+17+for+SQL+Server
    WAIT_TIME: [30,60]
    TYPE: [{"name":"vehicle", "provider":"VehicleProvider", "method":"fake.vehicle_object()"},{"name":"music","provider":"MusicProvider","method":"fake.music_genre_object()"}]
    STATUS:
      created: 50
      pending: 8
      shipped: 20
      delivered: 10
      others: 12
    NUM_PROCESSES: 1
    RETENTION_HOUR: 72
